services:
    front:
      build: ./front/my-app/
      ports:
        - 8080:80
      volumes:
        - ./front/:/data/front/
      working_dir: /data/front/my-app
      command: npm run dev
    back:
      build: ./back/my-back/
      ports: 
        - 8081:3000
      volumes:
       - ./back/:/data/back/
      working_dir: /data/back/my-back/
      command: npm run start